### ISSUE TITLE
运行出错：mkdir: cannot create directory '/home/build/openwrt/bin/targets': Permission denied

### ISSUE THREAD

**Issue by nnssz** [EkkoG/OpenWrt#1]
ubuntu 18.04 运行出错，请C大指点一下，感谢！

root@debian:~/ciel# ./run.sh amd64_21
Pulling imagebuilder_x86_64_21_02 (openwrtorg/imagebuilder:x86-64-21.02-SNAPSHOT)...
x86-64-21.02-SNAPSHOT: Pulling from openwrtorg/imagebuilder
1cfaf5c6f756: Pull complete
70e66b8a8157: Pull complete
bd6b7cd9a867: Pull complete
eb26ff370e39: Pull complete
5e043e6b2ccf: Pull complete
abea2a23e8a6: Pull complete
Digest: sha256:dbc4463293bb593687c7e236048bc2799789eb22a7c6026c0b40759249c554fe
Status: Downloaded newer image for openwrtorg/imagebuilder:x86-64-21.02-SNAPSHOT
Creating imagebuilder_x86_64_21_02 ... done
Attaching to imagebuilder_x86_64_21_02
imagebuilder_x86_64_21_02      | cd5844109a8e9dda
imagebuilder_x86_64_21_02      | Generate local signing keys...
imagebuilder_x86_64_21_02      | Generate local certificate...
imagebuilder_x86_64_21_02      | Checking 'working-make'... ok.
imagebuilder_x86_64_21_02      | Checking 'case-sensitive-fs'... ok.
imagebuilder_x86_64_21_02      | Checking 'proper-umask'... ok.
imagebuilder_x86_64_21_02      | Checking 'perl-data-dumper'... ok.
imagebuilder_x86_64_21_02      | Checking 'perl-findbin'... ok.
imagebuilder_x86_64_21_02      | Checking 'perl-file-copy'... ok.
imagebuilder_x86_64_21_02      | Checking 'perl-file-compare'... ok.
imagebuilder_x86_64_21_02      | Checking 'perl-thread-queue'... ok.
imagebuilder_x86_64_21_02      | Checking 'tar'... ok.
imagebuilder_x86_64_21_02      | Checking 'find'... ok.
imagebuilder_x86_64_21_02      | Checking 'bash'... ok.
imagebuilder_x86_64_21_02      | Checking 'xargs'... ok.
imagebuilder_x86_64_21_02      | Checking 'patch'... ok.
imagebuilder_x86_64_21_02      | Checking 'diff'... ok.
imagebuilder_x86_64_21_02      | Checking 'cp'... ok.
imagebuilder_x86_64_21_02      | Checking 'seq'... ok.
imagebuilder_x86_64_21_02      | Checking 'awk'... ok.
imagebuilder_x86_64_21_02      | Checking 'grep'... ok.
imagebuilder_x86_64_21_02      | Checking 'egrep'... ok.
imagebuilder_x86_64_21_02      | Checking 'getopt'... ok.
imagebuilder_x86_64_21_02      | Checking 'stat'... ok.
imagebuilder_x86_64_21_02      | Checking 'unzip'... ok.
imagebuilder_x86_64_21_02      | Checking 'bzip2'... ok.
imagebuilder_x86_64_21_02      | Checking 'wget'... ok.
imagebuilder_x86_64_21_02      | Checking 'perl'... ok.
imagebuilder_x86_64_21_02      | Checking 'python2-cleanup'... ok.
imagebuilder_x86_64_21_02      | Checking 'python'... ok.
imagebuilder_x86_64_21_02      | Checking 'python3'... ok.
imagebuilder_x86_64_21_02      | Checking 'python3-distutils'... ok.
imagebuilder_x86_64_21_02      | Checking 'git'... ok.
imagebuilder_x86_64_21_02      | Checking 'file'... ok.
imagebuilder_x86_64_21_02      | Checking 'rsync'... ok.
imagebuilder_x86_64_21_02      | Checking 'which'... ok.
imagebuilder_x86_64_21_02      | Checking 'ldconfig-stub'... ok.
imagebuilder_x86_64_21_02      | Building images for x86 - Generic x86/64
imagebuilder_x86_64_21_02      | Packages: luci luci-compat dnsmasq-full luci-i18n-base-zh-cn luci-i18n-firewall-zh-cn wget curl vim-full luci-app-clash overture clash luci-app-jd-dailybonus node luci-app-dnsfilter luci-app-zerotier luci-app-autoreboot luci-app-passwall luci-app-wrtbwmon luci-app-ssr-plus luci-theme-argon base-files busybox ca-bundle dropbear e2fsprogs firewall fstools ip6tables iptables kernel kmod-bnx2 kmod-button-hotplug kmod-e1000 kmod-e1000e kmod-forcedeth kmod-igb kmod-ipt-offload kmod-ixgbe kmod-r8169 libc libgcc libustream-wolfssl logd mkf2fs mtd netifd odhcp6c odhcpd-ipv6only opkg partx-utils ppp ppp-mod-pppoe procd uci uclient-fetch urandom-seed urngd
imagebuilder_x86_64_21_02      |
imagebuilder_x86_64_21_02      | mkdir: cannot create directory '/home/build/openwrt/bin/targets': Permission denied
imagebuilder_x86_64_21_02      | make[1]: *** [Makefile:120: _call_image] Error 1
imagebuilder_x86_64_21_02      | make: *** [Makefile:240: image] Error 2
imagebuilder_x86_64_21_02 exited with code 2
Going to remove imagebuilder_x86_64_21_02
Removing imagebuilder_x86_64_21_02 ... done

**Comment by EkkoG** [comment]
/home/build/openwrt/bin 是挂载到容器里的，/home/build/openwrt/bin/targets 是其子目录，这个权限问题看你环境，跟本配不上关系不是很大

**Comment by nnssz** [comment]
感谢Kevin大佬的回复。对docker不熟悉，以为按照网页说明来就好，自己先深入研究，再次感谢
！
发自我的iPhone

**Comment by SuZixiong** [comment]
我也遇到了如上情况，用非root用户或者root用户都是一样

**Comment by SuZixiong** [comment]
`chown -R 1000:1000 ./bin `可以解决
https://github.com/openwrt/docker/issues/43#issuecomment-604182888
