### ISSUE TITLE
没有 .env文件

### ISSUE THREAD

**Issue by lambdaplus** [EkkoG/OpenWrt#2]
你好，我遇到个问题，git下来，在Openwrt文件夹下没有找到 .env文件。是我哪里出问题了吗？--- WSL Ubuntu22.04

**Comment by EkkoG** [comment]
没有是正常的，自己新建一个即可，.env是配置文件，每个人的配置都不一样，项目里不会有这个文件

**Comment by lambdaplus** [comment]
原来是这样啊，好的，谢谢，我还以为哪里出问题了呢，谢谢！
