### ISSUE TITLE
Cannot use root-password module

### ISSUE THREAD

**Issue by raighnew** [EkkoG/OpenWrt#8]
这个 [commit](https://github.com/EkkoG/OpenWrt/commit/225f7a17d20af8beb95e59be9f3c38f84b4cf544)  导致使用root-password编译失败，重复的91-system

modules/root-password/files/etc/uci-defaults/91-system
modules/system/files/etc/uci-defaults/91-system

**Comment by EkkoG** [comment]
rename 其中一个就好了

**Comment by raighnew** [comment]
我暂时这么解决的，提个issue同步一下。
